services:
  postgres:
    container_name: back-pp
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamikaze
      POSTGRES_DB: backpp
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres